# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Lint
        run: ./gradlew lint
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: lint
          path: app/build/reports/lint-results.html
          
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: JUnit Test
        run: ./gradlew test
        
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: app/build/test-results/testDebugUnitTest/
          
  generate-apk:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
          
      - name: Build debug APK
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: 8-puzzle
          path: app/build/outputs/apk/debug/app-debug.apk
